In [5]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

In [6]:
class CSVDataset(Dataset):
    def __init__(self, csv_file):
        self.data = pd.read_csv(csv_file)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        feature = torch.tensor(self.data.iloc[idx, :-1].values, dtype=torch.float32)
        label = torch.tensor(self.data.iloc[idx, -1], dtype=torch.float32)
        return feature, label

In [7]:
dataset = CSVDataset("../../datasets/sample_data.csv")

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

In [8]:
for batch_idx, (features, labels) in enumerate(loader):
    print(f"Batch {batch_idx + 1}")
    print("Features shape:", features.shape)
    print("Labels shape:", labels.shape)
    print(features)
    print(labels)
    print("-" * 40)

Batch 1
Features shape: torch.Size([2, 2])
Labels shape: torch.Size([2])
tensor([[2.5000, 1.2000],
        [5.0000, 2.0000]])
tensor([0., 1.])
----------------------------------------
Batch 2
Features shape: torch.Size([2, 2])
Labels shape: torch.Size([2])
tensor([[1.0000, 0.8000],
        [4.5000, 3.9000]])
tensor([0., 1.])
----------------------------------------
Batch 3
Features shape: torch.Size([1, 2])
Labels shape: torch.Size([1])
tensor([[3.1000, 4.2000]])
tensor([1.])
----------------------------------------
