In [1]:
import torch
a = torch.zeros(3,4)
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [12]:
a = torch.tensor([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
print(a)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)
d = torch.matmul(b, a.T)
print(d)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[10, 10, 10],
        [26, 26, 26],
        [42, 42, 42]])


In [17]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(x[0:2,1:])
x = torch.arange(12)
print(x)
x= x.reshape(3,4)
print(x)

tensor([[2, 3],
        [5, 6]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = x.to(device)
print(x.device)

cpu


In [20]:
import torch

x = torch.tensor([[1.,2.],
                  [3.,4.]], requires_grad=True)

y = x * 2
z = y.mean()

z.backward()

print("Input:")
print(x)

print("\nGradient:")
print(x.grad)

Input:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

Gradient:
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
