In [10]:
import torch
a = torch.tensor(5)
print(a)
b = torch.tensor([1, 2, 3])
print(b)
c = torch.tensor([[1, 2, 5], [3, 4, 6]])
print(c)
print(c.shape)
print(c.dtype)
print(c.device)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2, 5],
        [3, 4, 6]])
torch.Size([2, 3])
torch.int64
cpu


In [11]:
import torch.nn as nn
from torchgen import model
model = nn.Sequential(
    nn.Linear(2, 2),
    nn.ReLU(),
    nn.Linear(2, 1)
)
x = torch.tensor([[1.0, 2.0]])
output = model(x)
print(output)

tensor([[-0.2259]], grad_fn=<AddmmBackward0>)


In [ ]:
model = nn.Sequential(
    nn.Linear(4, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 3)
)
x = torch.randn(5, 4)  # Batch of 5 samples, each with 4 features
output = model(x)
print(output)

tensor([[ 0.1972, -0.1692, -0.3624],
        [ 0.1209, -0.2159, -0.3070],
        [ 0.2165, -0.0878, -0.3279],
        [ 0.1221, -0.1962, -0.2756],
        [ 0.1164, -0.2179, -0.3091]], grad_fn=<AddmmBackward0>)
243
