In [1]:
import torch
queries = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],
    [0.0, 2.0, 0.0, 1.0],
    [1.0, 1.0, 0.0, 1.0]
])

keys = torch.tensor([
    [1.0, 0.0, 1.0, 1.0],
    [0.0, 2.0, 1.0, 0.0],
    [1.0, 1.0, 0.0, 1.0]
])

values = torch.tensor([
    [10.0, 20.0, 30.0, 40.0],
    [50.0, 60.0, 70.0, 80.0],
    [90.0, 100.0, 110.0, 120.0]
])
scores = queries @ keys.T

print("Similarity Scores:")
print(scores)
attention_weights = torch.softmax(scores, dim=1)

print("\nAttention Weights:")
print(attention_weights)
attention_output = attention_weights @ values

print("\nFinal Attention Output:")
print(attention_output)

Similarity Scores:
tensor([[2., 1., 1.],
        [1., 4., 3.],
        [2., 2., 3.]])

Attention Weights:
tensor([[0.5761, 0.2119, 0.2119],
        [0.0351, 0.7054, 0.2595],
        [0.2119, 0.2119, 0.5761]])

Final Attention Output:
tensor([[35.4330, 45.4330, 55.4330, 65.4330],
        [58.9751, 68.9751, 78.9751, 88.9751],
        [64.5670, 74.5670, 84.5670, 94.5670]])
